# Generated by Django 4.2.3 on 2023-10-13 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCredentials',
        ),
    ]
