# Generated by Django 4.2.3 on 2023-10-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
