# Generated by Django 4.2.3 on 2023-10-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp2',
            field=models.CharField(default='0000', max_length=25),
        ),
    ]
