# Generated by Django 4.2.3 on 2023-10-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userprofile_is_staff_alter_userprofile_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
    ]
