# Generated by Django 4.2.3 on 2023-10-29 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
